### ISSUE TITLE
Redirect to openwhisk.incubator.apache.org

### ISSUE THREAD

**Issue by jlengstorf** [apache/incubator-openwhisk-website#55]
After launch, we need to make this happen.

**Comment by krook** [comment]
There are probably a few steps we need to consider, and will rely on @mrutkows and Felix from Adobe to guide us. Such as:

- Procuring hosting resources/VM from Apache Foundation
- Configuring those resources to host our static (or dynamic) files
- Ensuring that openwhisk.org is a redirect rather than the explicit domain

**Comment by fmeschbe** [comment]
Infrastructure already exists at Apache for this static hosting. It is a matter of just putting the files there. Currently there are two ways how to do this as documented on the [project-site](http://www.apache.org/dev/project-site.html) page at Apache. 
I suggest in the immediate short term, once this new site is finalized, we do a manual upload of the site's content to the appropriate SVN location - just to have something up there.
We then work with Apache infra to see how

- we can automate the site update directly out of GitHub and 
- infra can setup the redirects

Makes sense ?

**Comment by krook** [comment]
This can be marked complete. @csantanapr?
